### ISSUE TITLE
package.json, missing zod in dev dependencies

### ISSUE THREAD

**Issue by YazidKurdi** [ai-ng/2txt#3]
```
https://nextjs.org/docs/messages/module-not-found



./node_modules/zod-to-json-schema/dist/esm/parsers/array.js:1:1
Module not found: Can't resolve 'zod'
> 1 | import { ZodFirstPartyTypeKind } from "zod";
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 | import { setResponseValueAndErrors } from "../errorMessages.js";
  3 | import { parseDef } from "../parseDef.js";
  4 | export function parseArrayDef(def, refs) {

```

**Comment by n1ckoates** [comment]
We're not using `zod`, and this looks like a dependency of another package. Did you change/add anything to the project?

**Comment by YazidKurdi** [comment]
Was testing out the app and found out that Anthropic's API is restricted by geolocation, the error occurs when trying to add an image with no API key, to reproduce:

1. yarn install
2. modifying extension postcss.config.cs --> postcss.config.cjs
3. yarn dev
4. adding an image

**Comment by n1ckoates** [comment]
An API key is required to deploy 2txt - does this issue happen even if you use `pnpm`?

**Comment by YazidKurdi** [comment]
Correct error is shown while using pnpm, weird...
```
 ⨯ Error: Could not resolve authentication method. Expected either apiKey or authToken to be set. Or for one of the "X-Api-Key" or "Authorization" headers to be explicitly omitted
```

**Comment by n1ckoates** [comment]
Regardless, we don't support other package managers, and an API key is required. Feel free to re-open this if you find a bug with this in `pnpm`, but if you modify the demo, you're on your own.
